language: r
cache: packages
sudo: false
latex: false

after_success:
- Rscript -e 'covr::codecov()'

notifications:
  slack:
    secure: YOxbPBFVAMbDbNc/6tDn5749/qOfJkM+hfTraG9LGstCZC2C4I7rxb3BRkUHphIbFuQiH8BW/L+BKPXkLBL8Hrz4uMMyD3RtMX1A9fZ9WizkHMT4GLCHE011TITiYIeJvv41R7RBuy6rn3RLpID5KeMTTDphIz1TOZdl1zsxqds=
  email:
    on_success: change
    on_failure: change
